FROM node:22-alpine
LABEL version="1.0.0" maintainer="ia@bancolombia.onmicrosoft.com" description="Backend de AIO"
WORKDIR /usr/src/app
COPY package.json .
COPY ./dist dist/
RUN npm install --omit=dev
RUN echo "hola mundo"
ENV CONTAINER_PORT 3001
EXPOSE 3001
RUN mkdir -p /home/node/.n8n \
 && chown -R node:node /home/node/.n8n
USER node
HEALTHCHECK NONE
ENV DEBUG=*
ENV NODE_DEBUG=*
CMD [ "npm", "run", "start" ]